# SPDX-FileCopyrightText: Copyright (c) 2026 Wataru Ashihara <wataash0607@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# mostly generated by codex

print('import')
import argparse
import tempfile
from pathlib import Path

import cv2
import numpy as np
import torch

from sam2.sam2_video_predictor import SAM2VideoPredictor


def overlay_mask(frame: np.ndarray, mask: np.ndarray) -> np.ndarray:
    out = frame.copy()
    out[mask] = (
        out[mask].astype(np.float32) * (1.0 - 0.45)
        + np.array([0, 200, 255], dtype=np.float32) * 0.45
    ).astype(np.uint8)
    return out


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="./test_in.mp4")
    parser.add_argument("--output-dir", default="./sam2_out")
    parser.add_argument("--mask", required=True)
    parser.add_argument("--frame-start", type=int, default=0)
    parser.add_argument("--frame-end", type=int, default=None)
    return parser.parse_args()


def main() -> None:
    print('main()')
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.is_absolute():
        input_path = Path(__file__).resolve().parent / input_path
    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = Path(__file__).resolve().parent / output_dir
    mask_path = None
    if args.mask is not None:
        mask_path = Path(args.mask)
        if not mask_path.is_absolute():
            mask_path = Path(__file__).resolve().parent / mask_path
    output_dir.mkdir(exist_ok=True)
    cap0 = cv2.VideoCapture(str(input_path))
    frame_count = int(cap0.get(cv2.CAP_PROP_FRAME_COUNT))
    if args.frame_end is None:
        frame_end = frame_count - 1
    else:
        frame_end = args.frame_end
    if not (0 <= args.frame_start < frame_count and 0 <= frame_end < frame_count):
        cap0.release()
        raise RuntimeError(
            f"invalid frame range: frame_start={args.frame_start} frame_end={frame_end} total_frames={frame_count}"
        )
    reverse = args.frame_start > frame_end
    clip_frame_start = min(args.frame_start, frame_end)
    clip_frame_end = max(args.frame_start, frame_end)
    start_frame_idx_in_clip = args.frame_start - clip_frame_start
    cap0.set(cv2.CAP_PROP_POS_FRAMES, args.frame_start)
    ok, frame0 = cap0.read()
    cap0.release()
    if not ok or frame0 is None:
        raise RuntimeError(
            f"failed to read start frame {args.frame_start}: {input_path}"
        )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"device: {device}")

    print(f'SAM2VideoPredictor.from_pretrained()')
    predictor = SAM2VideoPredictor.from_pretrained(
        "facebook/sam2.1-hiera-tiny",  # ~/.cache/huggingface/hub/models--facebook--sam2.1-hiera-tiny/
        device=device,
    )

    cap = cv2.VideoCapture(str(input_path))
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cv2.namedWindow("preview")

    written = 0
    with tempfile.TemporaryDirectory(prefix="sam2_clip_", dir=str(output_dir)) as temp_dir:
        clip_dir = Path(temp_dir)
        print(f'{clip_dir=}')
        for clip_idx, absolute_frame_idx in enumerate(
            range(clip_frame_start, clip_frame_end + 1)
        ):
            cap.set(cv2.CAP_PROP_POS_FRAMES, absolute_frame_idx)
            ok, clip_frame = cap.read()
            if not ok or clip_frame is None:
                cap.release()
                cv2.destroyAllWindows()
                raise RuntimeError(
                    f"failed to read clip frame {absolute_frame_idx}: {input_path}"
                )
            cv2.imwrite(str(clip_dir / f"{clip_idx:05d}.jpg"), clip_frame)

        inference_state = predictor.init_state(
            video_path=str(clip_dir),
            offload_video_to_cpu=(device == "cuda"),
        )

        with torch.inference_mode():
            if device == "cuda":
                autocast_context = torch.autocast("cuda", torch.bfloat16)
            else:
                autocast_context = torch.autocast("cpu", torch.bfloat16, enabled=False)

            with autocast_context:
                initial_mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
                if initial_mask is None:
                    raise RuntimeError(f"failed to read mask: {mask_path}")
                if initial_mask.shape != frame0.shape[:2]:
                    raise RuntimeError(
                        f"mask size mismatch: mask={initial_mask.shape} frame={frame0.shape[:2]}"
                    )
                predictor.add_new_mask(
                    inference_state=inference_state,
                    frame_idx=start_frame_idx_in_clip,
                    obj_id=1,
                    mask=(initial_mask != 0),
                )

                for out_frame_idx, out_obj_ids, out_mask_logits in predictor.propagate_in_video(
                    inference_state,
                    start_frame_idx=start_frame_idx_in_clip,
                    max_frame_num_to_track=abs(frame_end - args.frame_start),
                    reverse=reverse,
                ):
                    # print(f'{out_frame_idx=}, {out_obj_ids=}, {out_mask_logits.shape=}')
                    # assert out_obj_ids == [1]
                    # assert out_mask_logits.shape == torch.Size([1, 1, 720, 406])
                    # PyCharm debugger:
                    if False:
                        import matplotlib.pyplot as plt
                        plt.imshow(out_mask_logits[0, 0].detach().cpu().numpy(), cmap="gray")
                        plt.colorbar()
                        plt.show()
                    absolute_frame_idx = clip_frame_start + out_frame_idx
                    cap.set(cv2.CAP_PROP_POS_FRAMES, absolute_frame_idx)
                    ok, frame = cap.read()
                    if not ok:
                        break
                    mask = (out_mask_logits[0, 0] > 0.0).cpu().numpy()

                    frame = overlay_mask(
                        frame,
                        mask,
                    )
                    preview_jpg = frame.copy()
                    cv2.putText(
                        frame,
                        "Esc to stop",
                        (20, 40),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.8,
                        (255, 255, 255),
                        2,
                        cv2.LINE_AA,
                    )
                    cv2.putText(
                        frame,
                        f"frame={absolute_frame_idx}",
                        (20, int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) - 20),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.8,
                        (255, 255, 255),
                        2,
                        cv2.LINE_AA,
                    )
                    cv2.imwrite(
                        str(output_dir / f"preview.{absolute_frame_idx:04d}.jpg"),
                        preview_jpg,
                    )
                    cv2.imwrite(
                        str(output_dir / f"mask.{absolute_frame_idx:04d}.png"),
                        (mask.astype(np.uint8) * 255),
                    )
                    cv2.imshow("preview", frame)
                    written += 1
                    if cv2.waitKey(1) & 0xFF == 27:
                        break

    cap.release()
    cv2.destroyAllWindows()

    print(f"input : {input_path}")
    print(f"video frames: {frame_count}")
    print(f"tracked masks: {written}")


if __name__ == "__main__":
    main()
