#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Wataru Ashihara <wataash0607@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# mostly generated by codex
epilog = r'''
video_sam2.py -h
video_sam2.py track -h
video_sam2.py track --input in.mp4 --output_mask_dir sam2_mask/ --output_preview_dir sam2_preview/ --mask mask.png
video_sam2.py track --input in.mp4 --output_mask_dir sam2_mask/ --output_preview_dir sam2_preview/ --mask mask_f100.png --frame_start 100 --frame_end 200
video_sam2.py track --input in.mp4 --output_mask_dir sam2_mask/ --output_preview_dir sam2_preview/ --mask mask_f200.png --frame_start 200 --frame_end 100
video_sam2.py plan --input in.mp4 --output_mask_dir sam2_mask/ --output_preview_dir sam2_preview/ mask_manual_png/*.png
video_sam2.py plan --input in.mp4 --output_mask_dir sam2_mask/ --output_preview_dir sam2_preview/ mask_manual_png/*.png | bash
printf '0241-0259\n1237-1265\n1288-1464\n1832-1999-2828\n1832-2828,30\n' | video_sam2.py replan --color 39D3B5 --jpg_dir jpg/ --input in.mp4 --output_mask_dir sam2_mask/ --output_preview_dir sam2_preview/
'''[1:]

import argparse
import logging
import shlex
import sys
import tempfile
from pathlib import Path


try:
    from _colorize import get_colors  # Python 3.13+ (private API)
except ImportError:
    class _NoColors:
        RED = YELLOW = BLUE = WHITE = RESET = ""

    def get_colors(colorize=False, *, file=None):  # type: ignore[misc]
        return _NoColors


class MyFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        c = get_colors(file=sys.stderr)
        color = {
            logging.CRITICAL: c.RED,
            logging.ERROR: c.RED,
            logging.WARNING: c.YELLOW,
            logging.INFO: c.BLUE,
            logging.DEBUG: c.WHITE,
        }[record.levelno]
        fn = '' if record.funcName == '<module>' else f' {record.funcName}()'
        fmt = f'{color}[%(levelname)1.1s %(asctime)s %(filename)s:%(lineno)d{fn}] %(message)s{c.RESET}'
        return logging.Formatter(fmt=fmt, datefmt='%T').format(record)


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger_handler = logging.StreamHandler()
logger_handler.setFormatter(MyFormatter())
logger.addHandler(logger_handler)

logger.info('importing cv2, numpy, torch, sam2')
import cv2
import numpy as np
import torch

from sam2.sam2_video_predictor import SAM2VideoPredictor


class ArgumentDefaultsRawTextHelpFormatter(argparse.ArgumentDefaultsHelpFormatter, argparse.RawTextHelpFormatter):
    pass


def main() -> int:
    parser = argparse.ArgumentParser(formatter_class=ArgumentDefaultsRawTextHelpFormatter, epilog=epilog)
    parser.add_argument('-q', '--quiet', action='count', default=0,
                        help='decrease verbosity; default: debug, -q: info, -qq: warning, -qqq: error')
    subparsers = parser.add_subparsers(dest='subcommand_name', required=True)

    subparser = subparsers.add_parser('track', formatter_class=ArgumentDefaultsRawTextHelpFormatter)
    subparser.set_defaults(func=track)
    subparser.add_argument('--input', required=True)
    subparser.add_argument('--output_mask_dir', required=True)
    subparser.add_argument('--output_preview_dir', required=True)
    subparser.add_argument('--mask', required=True)
    subparser.add_argument('--frame_start', type=int, default=0)
    subparser.add_argument('--frame_end', type=int, default=None)
    subparser.add_argument('--no_gui', action='store_true', help='do not show the preview window (for headless environments; Esc-to-stop is unavailable)')

    subparser = subparsers.add_parser('plan', formatter_class=ArgumentDefaultsRawTextHelpFormatter)
    subparser.set_defaults(func=plan)
    subparser.add_argument('--input', required=True)
    subparser.add_argument('--output_mask_dir', required=True)
    subparser.add_argument('--output_preview_dir', required=True)
    subparser.add_argument('--no_gui', action='store_true', help='pass --no_gui to the generated track commands')
    subparser.add_argument('masks', nargs='+', help='mask PNGs whose basename is the frame number (e.g. mask_manual_png/0061.png)')

    subparser = subparsers.add_parser('replan', formatter_class=ArgumentDefaultsRawTextHelpFormatter)
    subparser.set_defaults(func=replan)
    subparser.add_argument('--input', required=True)
    subparser.add_argument('--output_mask_dir', required=True)
    subparser.add_argument('--output_preview_dir', required=True)
    subparser.add_argument('--jpg_dir', required=True)
    subparser.add_argument('--sam2_mask_dir', default='sam2_mask')
    subparser.add_argument('--mask_manual_xcf_dir', default='mask_manual_xcf')
    subparser.add_argument('--mask_manual_png_dir', default='mask_manual_png')
    subparser.add_argument('--color', required=True, help='color passed to sam2_mask_to_xcf.sh')
    subparser.add_argument('--xcf_layer', type=int, default=1, help='XCF layer index read by magick')
    subparser.add_argument('--no_gui', action='store_true', help='pass --no_gui to the generated track commands')
    subparser.add_argument(
        'ranges',
        nargs='*',
        help='ranges like 0241-0259, 1832-1999-2828 (explicit seed frame), or 1832-2828,30 (split into 30-frame chunks); stdin is used when omitted',
    )

    args = parser.parse_args()
    logger.setLevel({0: logging.DEBUG, 1: logging.INFO, 2: logging.WARNING}.get(args.quiet, logging.ERROR))
    logger.debug(f'{args=}')
    return args.func(args)


def plan(args: argparse.Namespace) -> int:
    masks = sorted(((int(Path(p).stem), Path(p)) for p in args.masks), key=lambda t: t[0])
    width = max(len(p.stem) for _, p in masks)
    cap = cv2.VideoCapture(args.input)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    if frame_count <= 0:
        raise RuntimeError(f'failed to get frame count: {args.input}')
    for i, (frame, mask_path) in enumerate(masks):
        base = f'time {sys.argv[0]} track{" --no_gui" if args.no_gui else ""} --input {args.input} --output_mask_dir {args.output_mask_dir} --output_preview_dir {args.output_preview_dir} --mask={mask_path}'
        # backward: to 0 for the first mask, to the midpoint with the previous mask otherwise
        end = 0 if i == 0 else (masks[i - 1][0] + frame) // 2
        print(f'{base} --frame_start={frame:0{width}d} --frame_end={end:0{width}d}')
        # forward: to the midpoint with the next mask, to the last frame for the last mask
        end = frame_count - 1 if i == len(masks) - 1 else (frame + masks[i + 1][0]) // 2
        print(f'{base} --frame_start={frame:0{width}d} --frame_end={end:0{width}d}')
    return 0


def shell_join(parts: list[str | Path]) -> str:
    return ' '.join(shlex.quote(str(part)) for part in parts)


def parse_replan_range(text: str) -> list[tuple[int, int, int, int]]:
    range_s, _, step_s = text.partition(',')
    parts = range_s.split('-')
    width = max(len(part) for part in parts)
    if step_s:
        # START-END,STEP: equivalent to START-(START+STEP) (START+STEP)-(START+2*STEP) ... -END
        if len(parts) != 2:
            raise ValueError(f'expected START-END,STEP: {text}')
        left, end = (int(part) for part in parts)
        step = int(step_s)
        if not (left < end and step > 0):
            raise ValueError(f'expected START < END and STEP > 0: {text}')
        out = []
        while left < end:
            right = min(left + step, end)
            out.append((left, (left + right) // 2, right, width))
            left = right
        return out
    if len(parts) == 2:
        left, right = (int(part) for part in parts)
        seed = (left + right) // 2
    elif len(parts) == 3:
        left, seed, right = (int(part) for part in parts)
    else:
        raise ValueError(f'expected START-END, START-SEED-END, or START-END,STEP: {text}')
    return [(left, seed, right, width)]


def read_replan_ranges(args: argparse.Namespace) -> list[str]:
    if args.ranges:
        lines = args.ranges
    else:
        lines = sys.stdin.read().splitlines()
    return [line.strip() for line in lines if line.strip() and not line.strip().startswith('#')]


def replan(args: argparse.Namespace) -> int:
    ranges = [r for line in read_replan_ranges(args) for r in parse_replan_range(line)]
    if not ranges:
        raise RuntimeError('no ranges provided')

    width = max(width for _, _, _, width in ranges)
    rows = [
        (left, seed, right, f'{seed:0{width}d}')
        for left, seed, right, _ in ranges
    ]

    for _, _, _, seed_s in rows:
        print(shell_join([
            'sam2_mask_to_xcf.sh',
            args.color,
            Path(args.jpg_dir) / f'{seed_s}.jpg',
            Path(args.sam2_mask_dir) / f'{seed_s}.png',
            Path(args.mask_manual_xcf_dir) / f'{seed_s}.xcf',
        ]))
    for _, _, _, seed_s in rows:
        print(shell_join(['gimp', Path(args.mask_manual_xcf_dir) / f'{seed_s}.xcf']))
    print()

    for _, _, _, seed_s in rows:
        print(shell_join([
            'magick',
            f'{Path(args.mask_manual_xcf_dir) / f"{seed_s}.xcf"}[{args.xcf_layer}]',
            '-alpha',
            'extract',
            '-negate',
            Path(args.mask_manual_png_dir) / f'{seed_s}.png',
        ]))
    print()

    for left, seed, right, seed_s in rows:
        base = [
            sys.argv[0],
            'track',
        ]
        if args.no_gui:
            base.append('--no_gui')
        base.extend([
            '--input',
            args.input,
            '--output_mask_dir',
            args.output_mask_dir,
            '--output_preview_dir',
            args.output_preview_dir,
            f'--mask={Path(args.mask_manual_png_dir) / f"{seed_s}.png"}',
            f'--frame_start={seed_s}',
        ])
        print('time ' + shell_join([*base, f'--frame_end={left:0{width}d}']))
        print('time ' + shell_join([*base, f'--frame_end={right:0{width}d}']))
    return 0


def overlay_mask(frame: np.ndarray, mask: np.ndarray) -> np.ndarray:
    out = frame.copy()
    out[mask] = (
        out[mask].astype(np.float32) * (1.0 - 0.45)
        + np.array([0, 200, 255], dtype=np.float32) * 0.45
    ).astype(np.uint8)
    return out


def track(args: argparse.Namespace) -> int:
    input_path = Path(args.input)
    output_mask_dir = Path(args.output_mask_dir)
    output_preview_dir = Path(args.output_preview_dir)
    mask_path = Path(args.mask)
    output_mask_dir.mkdir(exist_ok=True)
    output_preview_dir.mkdir(exist_ok=True)
    cap0 = cv2.VideoCapture(str(input_path))
    frame_count = int(cap0.get(cv2.CAP_PROP_FRAME_COUNT))
    if args.frame_end is None:
        frame_end = frame_count - 1
    else:
        frame_end = args.frame_end
    if not (0 <= args.frame_start < frame_count and 0 <= frame_end < frame_count):
        cap0.release()
        raise RuntimeError(
            f"invalid frame range: frame_start={args.frame_start} frame_end={frame_end} total_frames={frame_count}"
        )
    reverse = args.frame_start > frame_end
    clip_frame_start = min(args.frame_start, frame_end)
    clip_frame_end = max(args.frame_start, frame_end)
    start_frame_idx_in_clip = args.frame_start - clip_frame_start
    cap0.set(cv2.CAP_PROP_POS_FRAMES, args.frame_start)
    ok, frame0 = cap0.read()
    cap0.release()
    if not ok or frame0 is None:
        raise RuntimeError(
            f"failed to read start frame {args.frame_start}: {input_path}"
        )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"device: {device}")

    logger.info('SAM2VideoPredictor.from_pretrained()')
    predictor = SAM2VideoPredictor.from_pretrained(
        "facebook/sam2.1-hiera-tiny",  # ~/.cache/huggingface/hub/models--facebook--sam2.1-hiera-tiny/
        device=device,
    )

    cap = cv2.VideoCapture(str(input_path))
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if not args.no_gui:
        cv2.namedWindow("preview")

    written = 0
    with tempfile.TemporaryDirectory(prefix="sam2_clip_", dir=str(output_mask_dir)) as temp_dir:
        clip_dir = Path(temp_dir)
        logger.debug(f'{clip_dir=}')
        # sequential read: CAP_PROP_POS_FRAMES seeks are inaccurate on VFR videos
        # and fail on the last frame
        for skip_frame_idx in range(clip_frame_start):
            if not cap.grab():
                cap.release()
                if not args.no_gui:
                    cv2.destroyAllWindows()
                raise RuntimeError(
                    f"failed to skip frame {skip_frame_idx}: {input_path}"
                )
        for clip_idx, absolute_frame_idx in enumerate(
            range(clip_frame_start, clip_frame_end + 1)
        ):
            ok, clip_frame = cap.read()
            if not ok or clip_frame is None:
                cap.release()
                if not args.no_gui:
                    cv2.destroyAllWindows()
                raise RuntimeError(
                    f"failed to read clip frame {absolute_frame_idx}: {input_path}"
                )
            cv2.imwrite(str(clip_dir / f"{clip_idx:05d}.jpg"), clip_frame)

        inference_state = predictor.init_state(
            video_path=str(clip_dir),
            offload_video_to_cpu=(device == "cuda"),
        )

        with torch.inference_mode():
            if device == "cuda":
                autocast_context = torch.autocast("cuda", torch.bfloat16)
            else:
                autocast_context = torch.autocast("cpu", torch.bfloat16, enabled=False)

            with autocast_context:
                initial_mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
                if initial_mask is None:
                    raise RuntimeError(f"failed to read mask: {mask_path}")
                if initial_mask.shape != frame0.shape[:2]:
                    raise RuntimeError(
                        f"mask size mismatch: mask={initial_mask.shape} frame={frame0.shape[:2]}"
                    )
                predictor.add_new_mask(
                    inference_state=inference_state,
                    frame_idx=start_frame_idx_in_clip,
                    obj_id=1,
                    mask=(initial_mask != 0),
                )

                for out_frame_idx, out_obj_ids, out_mask_logits in predictor.propagate_in_video(
                    inference_state,
                    start_frame_idx=start_frame_idx_in_clip,
                    max_frame_num_to_track=abs(frame_end - args.frame_start),
                    reverse=reverse,
                ):
                    # logger.debug(f'{out_frame_idx=}, {out_obj_ids=}, {out_mask_logits.shape=}')
                    # assert out_obj_ids == [1]
                    # assert out_mask_logits.shape == torch.Size([1, 1, 720, 406])
                    # PyCharm debugger:
                    if False:
                        import matplotlib.pyplot as plt
                        plt.imshow(out_mask_logits[0, 0].detach().cpu().numpy(), cmap="gray")
                        plt.colorbar()
                        plt.show()
                    absolute_frame_idx = clip_frame_start + out_frame_idx
                    frame = cv2.imread(str(clip_dir / f"{out_frame_idx:05d}.jpg"))
                    if frame is None:
                        break
                    mask = (out_mask_logits[0, 0] > 0.0).cpu().numpy()

                    frame = overlay_mask(
                        frame,
                        mask,
                    )
                    preview_jpg = frame.copy()
                    if not args.no_gui:
                        cv2.putText(
                            frame,
                            "Esc to stop",
                            (20, 40),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.8,
                            (255, 255, 255),
                            2,
                            cv2.LINE_AA,
                        )
                        cv2.putText(
                            frame,
                            f"frame={absolute_frame_idx}",
                            (20, int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) - 20),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.8,
                            (255, 255, 255),
                            2,
                            cv2.LINE_AA,
                        )
                    cv2.imwrite(
                        str(output_preview_dir / f"{absolute_frame_idx:04d}.jpg"),
                        preview_jpg,
                    )
                    cv2.imwrite(
                        str(output_mask_dir / f"{absolute_frame_idx:04d}.png"),
                        (mask.astype(np.uint8) * 255),
                    )
                    written += 1
                    if not args.no_gui:
                        cv2.imshow("preview", frame)
                        if cv2.waitKey(1) & 0xFF == 27:
                            break

    cap.release()
    if not args.no_gui:
        cv2.destroyAllWindows()

    logger.info(f"input : {input_path}")
    logger.info(f"video frames: {frame_count}")
    logger.info(f"tracked masks: {written}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
