#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Wataru Ashihara <wataash0607@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# mostly generated by codex with gpt-5.4
epilog = r"""
video_crop_gui.py -h
video_crop_gui.py select -h
video_crop_gui.py select --time 83.456 input.mp4
video_crop_gui.py select --time f:120 input.mp4
video_crop_gui.py select --time 00:01:23.456 input.mp4
video_crop_gui.py select --time last input.mp4
"""[1:]

import argparse
import dataclasses
import io
import logging
import math
import pathlib
import subprocess
import sys
import tkinter as tk
import tkinter.font as tkfont
from tkinter import ttk

import cv2
import numpy as np
from PIL import Image, ImageTk
import requests

from lib_ import video_time


class MyFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        color = {
            logging.CRITICAL: "\x1b[31m",
            logging.ERROR: "\x1b[31m",
            logging.WARNING: "\x1b[33m",
            logging.INFO: "\x1b[34m",
            logging.DEBUG: "\x1b[37m",
        }[record.levelno]
        func_name = "" if record.funcName == "<module>" else f" {record.funcName}()"
        fmt = f"{color}[%(levelname)1.1s %(asctime)s %(filename)s:%(lineno)d{func_name}] %(message)s\x1b[m"
        return logging.Formatter(fmt=fmt, datefmt="%T").format(record)


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger_handler = logging.StreamHandler()
logger_handler.setFormatter(MyFormatter())
logger.addHandler(logger_handler)


class ArgumentDefaultsRawTextHelpFormatter(
    argparse.ArgumentDefaultsHelpFormatter, argparse.RawTextHelpFormatter
):
    pass


@dataclasses.dataclass
class Rect:
    x: int = 0
    y: int = 0
    w: int = 0
    h: int = 0

    def normalized(self) -> "Rect":
        x = self.x
        y = self.y
        w = self.w
        h = self.h
        if w < 0:
            x += w
            w = -w
        if h < 0:
            y += h
            h = -h
        return Rect(x, y, w, h)

    def clamp(self, max_w: int, max_h: int) -> "Rect":
        rect = self.normalized()
        x = max(0, min(rect.x, max_w))
        y = max(0, min(rect.y, max_h))
        w = max(0, min(rect.w, max_w - x))
        h = max(0, min(rect.h, max_h - y))
        return Rect(x, y, w, h)

    def crop_filter(self) -> str:
        rect = self.normalized()
        return f"crop={rect.w}:{rect.h}:{rect.x}:{rect.y}"

    def whxy(self) -> str:
        rect = self.normalized()
        return f"{rect.w}:{rect.h}:{rect.x}:{rect.y}"


class CropUI:
    def __init__(
        self,
        video_path: pathlib.Path,
        initial_time: video_time.TimeOrFrame,
        initial_rect: Rect | None = None,
    ) -> None:
        self.video_path = video_path
        self.cap = cv2.VideoCapture(str(video_path))
        if not self.cap.isOpened():
            raise SystemExit(f"failed to open video: {video_path}")

        self.frame_count = int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
        self.fps = self.cap.get(cv2.CAP_PROP_FPS) or 30.0
        self.video_w = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 0)
        self.video_h = int(self.cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 0)
        self.duration = self.frame_count / self.fps if self.frame_count and self.fps else 0.0
        self.target_scale = 1.0
        self.display_scale = 1.0

        self.root = tk.Tk()
        self.root.title(f"video-crop-gui: {video_path.name}")
        self.root.geometry(self._default_geometry())
        self.root.configure(background="#f3f4f6")
        self.root.bind("<Left>", lambda _: self.step_frame(-1))
        self.root.bind("<Right>", lambda _: self.step_frame(1))
        self.root.bind("<Shift-Left>", lambda _: self.step_frame(-10))
        self.root.bind("<Shift-Right>", lambda _: self.step_frame(10))
        self.root.bind("<Home>", lambda _: self.goto_frame(0))
        if self.frame_count:
            self.root.bind("<End>", lambda _: self.goto_frame(self.frame_count - 1))
        self.root.bind("<space>", self.on_space_shortcut)
        self.root.bind("<KeyPress>", self.on_keypress)

        self.current_frame_index = 0
        self.current_image = None
        self.current_bgr = None
        self.dragging = False
        self.drag_start = (0, 0)
        self.drag_mode = "new"
        self.drag_offset = (0, 0)
        self.drag_handle = ""
        self.drag_rect_origin = Rect()
        self.rect = (initial_rect or Rect()).clamp(self.video_w, self.video_h)
        self.canvas_image_id = None
        self.canvas_width = max(1, int(self.video_w * self.target_scale))
        self.canvas_height = max(1, int(self.video_h * self.target_scale))
        self.min_canvas_height = 120
        self.is_playing = False
        self.playback_after_id = None
        self.frame_delay_ms = max(1, int(round(1000.0 / self.fps)))
        self.ignore_seek_callback = False
        self.button_reset_after_id: dict[ttk.Button, str | None] = {}

        self._configure_styles()
        self._build_ui()
        self._configure_window_limits()

        start_frame = 0
        if self.frame_count:
            start_frame = video_time.resolve_frame_index(initial_time, self.fps, self.frame_count)
        self.goto_frame(start_frame)

    def _default_geometry(self) -> str:
        window_w = min(1400, max(900, self.video_w + 120))
        window_h = min(1000, max(720, self.video_h + 180))
        return f"{window_w}x{window_h}"

    def _pick_font_family(self, *preferred: str) -> str:
        families = {name.lower(): name for name in tkfont.families(self.root)}
        for family in preferred:
            if family.lower() in families:
                return families[family.lower()]
        return tkfont.nametofont("TkDefaultFont").actual("family")

    def _configure_styles(self) -> None:
        self.style = ttk.Style(self.root)
        if "clam" in self.style.theme_names():
            self.style.theme_use("clam")

        mono_family = self._pick_font_family(
            "Courier 10 Pitch",
            "TeX Gyre Cursor",
            "texgyrecursor",
            "Courier 10 Pitch",
            "Nimbus Mono PS",
            "TkFixedFont",
        )
        ui_family = self._pick_font_family(
            "TeX Gyre Heros",
            "texgyreheros",
            "Latin Modern Sans",
            "Nimbus Sans L",
            "Helvetica",
            "Arial",
            "TkDefaultFont",
        )

        self.ui_font = tkfont.Font(self.root, family=ui_family, size=12)
        self.meta_font = tkfont.Font(self.root, family=mono_family, size=13)
        self.button_font = tkfont.Font(self.root, family=ui_family, size=12)

        self.style.configure(".", font=self.ui_font)
        self.style.configure("TFrame", background="#f3f4f6")
        self.style.configure(
            "Meta.TLabel",
            font=self.meta_font,
            background="#f3f4f6",
            foreground="#111827",
            padding=(0, 1),
        )
        self.style.configure(
            "TButton",
            font=self.button_font,
            padding=(12, 6),
        )
        self.style.configure("TScale", background="#f3f4f6")

    def create_meta_text(self, parent: ttk.Frame, height: int = 1, wrap: str = "none") -> tk.Text:
        widget = tk.Text(
            parent,
            height=height,
            wrap=wrap,
            font=self.meta_font,
            background="#f3f4f6",
            foreground="#111827",
            borderwidth=0,
            highlightthickness=0,
            padx=0,
            pady=1,
            insertwidth=0,
            takefocus=1,
        )
        widget.pack(fill="x", anchor="w")
        widget.bind("<Control-c>", lambda event: event.widget.event_generate("<<Copy>>"))
        widget.bind("<Command-c>", lambda event: event.widget.event_generate("<<Copy>>"))
        return widget

    def set_meta_text(self, widget: tk.Text, text: str) -> None:
        widget.configure(state="normal")
        widget.delete("1.0", "end")
        widget.insert("1.0", text)
        widget.configure(state="disabled")

    def _build_ui(self) -> None:
        self.outer = ttk.Frame(self.root, padding=12)
        self.outer.pack(fill="both", expand=True)
        self.outer.columnconfigure(0, weight=1)
        self.outer.rowconfigure(0, weight=1)
        self.outer.rowconfigure(1, weight=0)

        self.canvas_container = ttk.Frame(self.outer)
        self.canvas_container.grid(row=0, column=0, sticky="nsew")
        self.canvas_container.columnconfigure(0, weight=1)
        self.canvas_container.rowconfigure(0, weight=1)

        self.canvas = tk.Canvas(
            self.canvas_container,
            width=self.canvas_width,
            height=self.canvas_height,
            bg="black",
            highlightthickness=0,
            cursor="crosshair",
        )
        self.canvas.grid(row=0, column=0, sticky="nsew")
        self.canvas.bind("<Configure>", self.on_canvas_configure)
        self.canvas.bind("<Motion>", self.on_canvas_motion)
        self.canvas.bind("<Leave>", self.on_canvas_leave)
        self.canvas.bind("<ButtonPress-1>", self.on_press)
        self.canvas.bind("<B1-Motion>", self.on_drag)
        self.canvas.bind("<ButtonRelease-1>", self.on_release)

        self.controls = ttk.Frame(self.outer, padding=(0, 10, 0, 0))
        self.controls.grid(row=1, column=0, sticky="ew")

        self.timeline = ttk.Scale(
            self.controls,
            from_=0,
            to=max(0, self.frame_count - 1),
            orient="horizontal",
            command=self.on_seek,
        )
        self.timeline.pack(fill="x")
        self.timeline.bind("<Button-1>", self.on_timeline_click, add="+")

        meta = ttk.Frame(self.controls, padding=(0, 8, 0, 0))
        meta.pack(fill="x")

        self.position_text = self.create_meta_text(meta)
        self.rect_text = self.create_meta_text(meta)
        self.command_text = self.create_meta_text(meta, height=2, wrap="word")
        self.status_text = self.create_meta_text(meta)
        self.set_meta_text(
            self.status_text,
            "drag to select, Shift+arrows for 10 frames",
        )
        self.root.bind("<Configure>", self.on_configure)

        buttons = ttk.Frame(self.controls, padding=(0, 8, 0, 0))
        buttons.pack(fill="x")
        ttk.Button(buttons, text="Prev (Left)", command=lambda: self.step_frame(-1)).pack(side="left")
        ttk.Button(buttons, text="Next (Right)", command=lambda: self.step_frame(1)).pack(side="left", padx=(8, 0))
        self.play_button = ttk.Button(buttons, text="Play (Space)", command=self.toggle_playback)
        self.play_button.pack(side="left", padx=(8, 0))
        self.reset_rect_button = ttk.Button(buttons, text="Reset Rect (r)", command=self.reset_rect)
        self.reset_rect_button.pack(side="left", padx=(8, 0))
        self.copy_crop_button = ttk.Button(buttons, text="Copy Crop (c)", command=self.copy_crop)
        self.copy_crop_button.pack(side="left", padx=(8, 0))
        self.copy_ffmpeg_button = ttk.Button(buttons, text="Copy ffmpeg (C)", command=self.copy_ffmpeg_command)
        self.copy_ffmpeg_button.pack(side="left", padx=(8, 0))

    def _configure_window_limits(self) -> None:
        self.root.update_idletasks()
        outer_padding = 24
        controls_height = self.controls.winfo_reqheight()
        min_width = 720
        min_height = outer_padding + controls_height + self.min_canvas_height
        self.root.minsize(min_width, min_height)
        self.canvas_container.configure(height=self.min_canvas_height)

    def on_configure(self, event: tk.Event) -> None:
        if event.widget is self.root:
            chars = max(40, (event.width - 48) // max(1, self.meta_font.measure("0")))
            self.command_text.configure(width=chars)

    def on_canvas_configure(self, event: tk.Event) -> None:
        new_width = max(1, event.width)
        new_height = max(1, event.height)
        if new_width == self.canvas_width and new_height == self.canvas_height:
            return
        self.canvas_width = new_width
        self.canvas_height = new_height
        if self.current_bgr is not None:
            self.render_frame()
            self.update_labels()

    def fit_scale(self) -> float:
        fit_by_width = self.canvas_width / self.video_w if self.video_w else 1.0
        fit_by_height = self.canvas_height / self.video_h if self.video_h else 1.0
        return max(0.01, min(fit_by_width, fit_by_height))

    def on_seek(self, raw_value: str) -> None:
        if self.ignore_seek_callback:
            return
        self.stop_playback()
        frame_index = int(float(raw_value))
        if frame_index != self.current_frame_index:
            self.goto_frame(frame_index)

    def has_modifier(self, event: tk.Event) -> bool:
        return bool(event.state & 0x4 or event.state & 0x8)

    def on_space_shortcut(self, event: tk.Event) -> str | None:
        if self.has_modifier(event):
            return None
        return self.toggle_playback()

    def on_keypress(self, event: tk.Event) -> str | None:
        if self.has_modifier(event):
            return None
        char = getattr(event, "char", "")
        if char == "c":
            self.copy_crop()
            return "break"
        if char == "C":
            self.copy_ffmpeg_command()
            return "break"
        if char == "r":
            self.reset_rect()
            return "break"
        if char == "q":
            self.root.destroy()
            return "break"
        return None

    def on_timeline_click(self, event: tk.Event) -> str | None:
        if self.frame_count <= 1:
            return "break"

        element = self.timeline.identify(event.x, event.y)
        if element == "slider":
            return None

        self.stop_playback()
        width = max(1, self.timeline.winfo_width())
        ratio = min(1.0, max(0.0, event.x / width))
        frame_index = int(round(ratio * (self.frame_count - 1)))
        self.goto_frame(frame_index)
        return "break"

    def update_play_button(self) -> None:
        self.play_button.configure(text="Pause (Space)" if self.is_playing else "Play (Space)")

    def flash_button_text(self, button: ttk.Button, temporary_text: str, original_text: str) -> None:
        after_id = self.button_reset_after_id.get(button)
        if after_id is not None:
            self.root.after_cancel(after_id)
        button.configure(text=temporary_text)
        self.button_reset_after_id[button] = self.root.after(
            900,
            lambda: self.restore_button_text(button, original_text),
        )

    def restore_button_text(self, button: ttk.Button, text: str) -> None:
        button.configure(text=text)
        self.button_reset_after_id[button] = None

    def stop_playback(self) -> None:
        if self.playback_after_id is not None:
            self.root.after_cancel(self.playback_after_id)
            self.playback_after_id = None
        if self.is_playing:
            self.is_playing = False
        self.update_play_button()

    def toggle_playback(self) -> str:
        if self.is_playing:
            self.stop_playback()
            self.update_labels()
            return "break"

        if self.current_frame_index >= max(0, self.frame_count - 1):
            self.goto_frame(0)
        self.is_playing = True
        self.update_play_button()
        self.schedule_next_frame()
        self.update_labels()
        return "break"

    def schedule_next_frame(self) -> None:
        if self.playback_after_id is not None:
            self.root.after_cancel(self.playback_after_id)
        self.playback_after_id = self.root.after(self.frame_delay_ms, self.play_next_frame)

    def play_next_frame(self) -> None:
        self.playback_after_id = None
        if not self.is_playing:
            return
        if self.current_frame_index >= max(0, self.frame_count - 1):
            self.stop_playback()
            self.set_meta_text(self.status_text, "reached end")
            self.update_labels()
            return
        self.goto_frame(self.current_frame_index + 1)
        if self.is_playing:
            self.schedule_next_frame()

    def goto_frame(self, frame_index: int) -> None:
        if self.frame_count:
            frame_index = max(0, min(frame_index, self.frame_count - 1))
        else:
            frame_index = max(0, frame_index)
        self.cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)
        ok, frame = self.cap.read()
        if not ok:
            frame = self.read_frame_with_ffmpeg(frame_index)
            if frame is None:
                self.set_meta_text(self.status_text, f"failed to read frame {frame_index}")
                return
        self.current_frame_index = frame_index
        self.current_bgr = frame
        self.render_frame()
        self.ignore_seek_callback = True
        try:
            self.timeline.set(frame_index)
        finally:
            self.ignore_seek_callback = False
        self.update_labels()

    def read_frame_with_ffmpeg(self, frame_index: int) -> np.ndarray | None:
        if self.fps <= 0:
            return None
        timestamp = max(0.0, frame_index / self.fps)
        try:
            result = subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-v",
                    "error",
                    "-ss",
                    f"{timestamp:.6f}",
                    "-i",
                    str(self.video_path),
                    "-frames:v",
                    "1",
                    "-f",
                    "image2pipe",
                    "-vcodec",
                    "png",
                    "-",
                ],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            image = Image.open(io.BytesIO(result.stdout)).convert("RGB")
        except (OSError, subprocess.CalledProcessError, Image.UnidentifiedImageError) as exc:
            logger.warning("ffmpeg fallback failed for frame %s: %s", frame_index, exc)
            return None
        frame_rgb = np.array(image)
        return cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR)

    def render_frame(self) -> None:
        self.display_scale = self.fit_scale()
        frame_rgb = cv2.cvtColor(self.current_bgr, cv2.COLOR_BGR2RGB)
        scaled_w = max(1, int(round(self.video_w * self.display_scale)))
        scaled_h = max(1, int(round(self.video_h * self.display_scale)))
        if not math.isclose(self.display_scale, 1.0):
            scaled = cv2.resize(
                frame_rgb,
                (scaled_w, scaled_h),
                interpolation=cv2.INTER_LINEAR if self.display_scale > 1.0 else cv2.INTER_AREA,
            )
        else:
            scaled = frame_rgb
        image = Image.fromarray(scaled)
        self.current_image = ImageTk.PhotoImage(image=image)
        self.canvas.delete("all")
        x = (self.canvas_width - image.width) // 2
        y = (self.canvas_height - image.height) // 2
        self.canvas_image_id = self.canvas.create_image(x, y, anchor="nw", image=self.current_image)
        self.draw_rect()

    def canvas_to_video(self, x: float, y: float) -> tuple[int, int]:
        image_x, image_y = self.image_origin()
        vx = int(round((x - image_x) / self.display_scale))
        vy = int(round((y - image_y) / self.display_scale))
        vx = max(0, min(vx, self.video_w))
        vy = max(0, min(vy, self.video_h))
        return vx, vy

    def video_to_canvas(self, x: int, y: int) -> tuple[int, int]:
        image_x, image_y = self.image_origin()
        return (
            image_x + int(round(x * self.display_scale)),
            image_y + int(round(y * self.display_scale)),
        )

    def image_origin(self) -> tuple[int, int]:
        image_w = int(round(self.video_w * self.display_scale))
        image_h = int(round(self.video_h * self.display_scale))
        return (
            max(0, (self.canvas_width - image_w) // 2),
            max(0, (self.canvas_height - image_h) // 2),
        )

    def point_in_rect(self, x: int, y: int, rect: Rect) -> bool:
        normalized = rect.clamp(self.video_w, self.video_h)
        if normalized.w <= 0 or normalized.h <= 0:
            return False
        return (
            normalized.x <= x <= normalized.x + normalized.w
            and normalized.y <= y <= normalized.y + normalized.h
        )

    def handle_margin(self) -> int:
        return max(4, int(round(10 / max(self.display_scale, 0.01))))

    def rect_hit_zone(self, x: int, y: int, rect: Rect) -> str:
        normalized = rect.clamp(self.video_w, self.video_h)
        if normalized.w <= 0 or normalized.h <= 0:
            return ""
        if not self.point_in_rect(x, y, normalized):
            return ""

        margin = self.handle_margin()
        left = abs(x - normalized.x) <= margin
        right = abs(x - (normalized.x + normalized.w)) <= margin
        top = abs(y - normalized.y) <= margin
        bottom = abs(y - (normalized.y + normalized.h)) <= margin

        if top and left:
            return "nw"
        if top and right:
            return "ne"
        if bottom and left:
            return "sw"
        if bottom and right:
            return "se"
        if left:
            return "w"
        if right:
            return "e"
        if top:
            return "n"
        if bottom:
            return "s"
        return "move"

    def resize_rect(self, origin: Rect, handle: str, x: int, y: int) -> Rect:
        rect = origin.clamp(self.video_w, self.video_h)
        left = rect.x
        top = rect.y
        right = rect.x + rect.w
        bottom = rect.y + rect.h

        if "w" in handle:
            left = min(max(0, x), right - 1)
        if "e" in handle:
            right = max(min(self.video_w, x), left + 1)
        if "n" in handle:
            top = min(max(0, y), bottom - 1)
        if "s" in handle:
            bottom = max(min(self.video_h, y), top + 1)

        return Rect(left, top, right - left, bottom - top).clamp(self.video_w, self.video_h)

    def update_canvas_cursor(self, x: int | None = None, y: int | None = None) -> None:
        if self.dragging and self.drag_mode == "move":
            self.canvas.configure(cursor="fleur")
            return
        if self.dragging and self.drag_mode == "resize":
            cursor = {
                "n": "sb_v_double_arrow",
                "s": "sb_v_double_arrow",
                "e": "sb_h_double_arrow",
                "w": "sb_h_double_arrow",
                "ne": "top_right_corner",
                "sw": "bottom_left_corner",
                "nw": "top_left_corner",
                "se": "bottom_right_corner",
            }.get(self.drag_handle, "crosshair")
            self.canvas.configure(cursor=cursor)
            return
        if x is None or y is None:
            self.canvas.configure(cursor="crosshair")
            return
        vx, vy = self.canvas_to_video(x, y)
        zone = self.rect_hit_zone(vx, vy, self.rect)
        cursor = {
            "move": "fleur",
            "n": "sb_v_double_arrow",
            "s": "sb_v_double_arrow",
            "e": "sb_h_double_arrow",
            "w": "sb_h_double_arrow",
            "ne": "top_right_corner",
            "sw": "bottom_left_corner",
            "nw": "top_left_corner",
            "se": "bottom_right_corner",
            "": "crosshair",
        }[zone]
        self.canvas.configure(cursor=cursor)

    def on_canvas_motion(self, event: tk.Event) -> None:
        self.update_canvas_cursor(event.x, event.y)

    def on_canvas_leave(self, _event: tk.Event) -> None:
        if not self.dragging:
            self.update_canvas_cursor()

    def on_press(self, event: tk.Event) -> None:
        self.stop_playback()
        self.dragging = True
        vx, vy = self.canvas_to_video(event.x, event.y)
        current_rect = self.rect.clamp(self.video_w, self.video_h)
        zone = self.rect_hit_zone(vx, vy, current_rect)
        if zone == "move":
            self.drag_mode = "move"
            self.drag_offset = (vx - current_rect.x, vy - current_rect.y)
            self.rect = current_rect
        elif zone:
            self.drag_mode = "resize"
            self.drag_handle = zone
            self.drag_rect_origin = current_rect
            self.rect = current_rect
        else:
            self.drag_mode = "new"
            self.drag_start = (vx, vy)
            self.rect = Rect(vx, vy, 0, 0)
        self.render_frame()
        self.update_canvas_cursor(event.x, event.y)
        self.update_labels()

    def on_drag(self, event: tk.Event) -> None:
        if not self.dragging:
            return
        vx, vy = self.canvas_to_video(event.x, event.y)
        if self.drag_mode == "move":
            current = self.rect.clamp(self.video_w, self.video_h)
            next_x = vx - self.drag_offset[0]
            next_y = vy - self.drag_offset[1]
            next_x = max(0, min(next_x, self.video_w - current.w))
            next_y = max(0, min(next_y, self.video_h - current.h))
            self.rect = Rect(next_x, next_y, current.w, current.h)
        elif self.drag_mode == "resize":
            self.rect = self.resize_rect(self.drag_rect_origin, self.drag_handle, vx, vy)
        else:
            self.rect = Rect(
                self.drag_start[0],
                self.drag_start[1],
                vx - self.drag_start[0],
                vy - self.drag_start[1],
            )
        self.render_frame()
        self.update_canvas_cursor(event.x, event.y)
        self.update_labels()

    def on_release(self, event: tk.Event) -> None:
        self.dragging = False
        vx, vy = self.canvas_to_video(event.x, event.y)
        if self.drag_mode == "move":
            self.rect = self.rect.clamp(self.video_w, self.video_h)
        elif self.drag_mode == "resize":
            self.rect = self.resize_rect(self.drag_rect_origin, self.drag_handle, vx, vy)
        else:
            self.rect = Rect(
                self.drag_start[0],
                self.drag_start[1],
                vx - self.drag_start[0],
                vy - self.drag_start[1],
            ).clamp(self.video_w, self.video_h)
        self.drag_mode = "new"
        self.drag_handle = ""
        self.render_frame()
        self.update_canvas_cursor(event.x, event.y)
        self.update_labels()

    def draw_rect(self) -> None:
        rect = self.rect.normalized()
        if rect.w <= 0 or rect.h <= 0:
            return
        x1, y1 = self.video_to_canvas(rect.x, rect.y)
        x2, y2 = self.video_to_canvas(rect.x + rect.w, rect.y + rect.h)
        self.canvas.create_rectangle(x1, y1, x2, y2, outline="#00ff88", width=2)

    def step_frame(self, delta: int) -> None:
        self.stop_playback()
        self.goto_frame(self.current_frame_index + delta)

    def reset_rect(self) -> None:
        self.rect = Rect()
        self.render_frame()
        self.update_labels()
        self.flash_button_text(self.reset_rect_button, "Reset", "Reset Rect (r)")

    def current_crop(self) -> str:
        rect = self.rect.clamp(self.video_w, self.video_h)
        if rect.w <= 0 or rect.h <= 0:
            return "crop=0:0:0:0"
        return rect.crop_filter()

    def current_rect_whxy(self) -> str:
        rect = self.rect.clamp(self.video_w, self.video_h)
        if rect.w <= 0 or rect.h <= 0:
            return "0:0:0:0"
        return rect.whxy()

    def ffmpeg_command(self) -> str:
        crop = self.current_crop()
        return (
            f'ffmpeg -i "{self.video_path}" -vf "{crop}" '
            f'-c:v libx264 -crf 18 -preset medium -c:a copy out.crop.mp4'
        )

    def copy_crop(self) -> None:
        crop = self.current_crop()
        self.root.clipboard_clear()
        self.root.clipboard_append(crop)
        self.flash_button_text(self.copy_crop_button, "Copied", "Copy Crop (c)")

    def copy_ffmpeg_command(self) -> None:
        command = self.ffmpeg_command()
        self.root.clipboard_clear()
        self.root.clipboard_append(command)
        self.flash_button_text(self.copy_ffmpeg_button, "Copied", "Copy ffmpeg (C)")

    def update_labels(self) -> None:
        seconds = self.current_frame_index / self.fps if self.fps else 0.0
        self.set_meta_text(
            self.position_text,
            f"frame: {self.current_frame_index}/{max(0, self.frame_count - 1)}  "
            f"time: {seconds:.3f}s / {self.duration:.3f}s  "
            f"video: {self.video_w}x{self.video_h}  display scale: {self.display_scale:.4f}"
        )
        rect = self.rect.clamp(self.video_w, self.video_h)
        if rect.w > 0 and rect.h > 0:
            self.set_meta_text(self.rect_text, f"rect: x={rect.x} y={rect.y} w={rect.w} h={rect.h}")
        else:
            self.set_meta_text(self.rect_text, "rect: none")
        self.set_meta_text(self.command_text, self.ffmpeg_command())

    def run(self) -> None:
        self.root.mainloop()
        self.playback_after_id = None
        self.is_playing = False
        self.cap.release()


def main() -> int:
    parser = argparse.ArgumentParser(
        formatter_class=ArgumentDefaultsRawTextHelpFormatter,
        epilog=epilog,
    )
    subparsers = parser.add_subparsers(dest="subcommand_name", required=True)

    subparser = subparsers.add_parser(
        "select",
        formatter_class=ArgumentDefaultsRawTextHelpFormatter,
        help="open GUI and interactively choose ffmpeg crop=w:h:x:y",
    )
    subparser.set_defaults(func=select)
    subparser.add_argument("input", help="input video path")
    subparser.add_argument(
        "--time",
        type=video_time.parse_time_or_frame,
        help="initial seek position as seconds, hh:mm:ss.mmm, frame:N/f:N, or last",
    )
    subparser.add_argument(
        "--rect",
        type=parse_whxy_rect,
        metavar="W:H:X:Y",
        default=None,
        help="initial rectangle as w:h:x:y",
    )
    subparser.add_argument(
        "--crop",
        dest="rect",
        type=parse_whxy_rect,
        metavar="W:H:X:Y",
        help="alias for --rect",
    )

    args = parser.parse_args()
    logger.debug("%s", args)
    return args.func(args)


def parse_whxy_rect(raw: str) -> Rect:
    parts = raw.split(":")
    if len(parts) != 4:
        raise argparse.ArgumentTypeError("expected W:H:X:Y")
    try:
        w, h, x, y = (int(part) for part in parts)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("expected integer W:H:X:Y") from exc
    if w < 0 or h < 0:
        raise argparse.ArgumentTypeError("W and H must be non-negative")
    return Rect(x=x, y=y, w=w, h=h)


def select(args: argparse.Namespace) -> int:
    _ = requests
    video_path = pathlib.Path(args.input)
    if not video_path.exists():
        print(f"input not found: {video_path}", file=sys.stderr)
        return 1

    initial_time = args.time or video_time.TimeOrFrame(kind="time", value=0)
    app = CropUI(video_path=video_path, initial_time=initial_time, initial_rect=args.rect)
    app.run()
    print(app.current_rect_whxy())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
